dist: xenial
language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "pypy"
install:
 - pip install --upgrade pip
 - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install pylzma; fi"
 - "pip install .[test]"
script:
 - pylint pysparkling
 - python -m pytest -vv
