name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.5
          - os: ubuntu-latest
            python: 3.6
          - os: ubuntu-latest
            python: 3.7
          - os: ubuntu-latest
            python: 3.8
          - os: ubuntu-latest
            python: 3.9
          - os: macos-latest
            python: 3.7
          - os: windows-latest
            python: 3.7

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[test]" --use-deprecated=legacy-resolver
    - name: Print environment
      run: |
        python -m pip freeze
        python --version
        python -c "import pysparkling; print(pysparkling.__version__)"
    - name: Lint
      run: pylint pysparkling --disable=fixme
    - name: pycodestyle
      run: python -m pycodestyle pysparkling
    - name: Test
      run: python -m pytest -vv
      env:
        PYTHONIOENCODING: utf8
