name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.5
          - os: ubuntu-latest
            python: 3.6
          - os: ubuntu-latest
            python: 3.7
          - os: ubuntu-latest
            python: 3.8
          - os: ubuntu-latest
            python: 3.9
          - os: macos-latest
            python: 3.7
          - os: windows-latest
            python: 3.7

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[tests]" --use-deprecated=legacy-resolver
    - name: Print environment
      run: |
        python -m pip freeze
        python --version
        python -c "import pysparkling; print(pysparkling.__version__)"
    - name: Test Core
      if: matrix.os != 'windows-latest'  # because of path separator
      run: python -m pytest pysparkling/rdd.py -vv
    - name: Install SQL Dependencies
      run: |
        python -m pip install -e ".[sql]" --use-deprecated=legacy-resolver
    - name: Lint
      run: pylint pysparkling --disable=fixme
    - name: pycodestyle
      run: python -m pycodestyle pysparkling
    - name: Test All
      run: python -m pytest -vv --ignore=pysparkling.streaming.context.StreamingContext.queueStream,pysparkling.streaming.dstream.DStream.cogroup,pysparkling.streaming.dstream.DStream.map,pysparkling.streaming.dstream.DStream.saveAsTextFiles,pysparkling/tests/test_streaming_queue.py
